# Stage 1: Build
FROM node:20-alpine AS builder
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build --workspace apps/control-panel-client
RUN npm run build --workspace apps/control-panel-server

# Stage 2: Runner
FROM node:20-alpine AS runner
WORKDIR /app

COPY --from=builder /app/apps/control-panel-server/dist ./dist
COPY --from=builder /app/apps/control-panel-server/package.json ./package.json
COPY --from=builder /app/apps/control-panel-client/dist ./dist/public
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 8001
CMD ["node", "dist/index.js"]