# TYPE  DATABASE        USER            ADDRESS                 METHOD
# Allow Unix socket connections inside the container
local   all             all                                     trust

# Allow Docker-network clients (e.g. paperless app container)
host    all             all             172.16.0.0/12           trust

# Allow TCP clients from anywhere
host    all             all             0.0.0.0/0               trust
host    all             all             ::/0                    trust
